import type { Product } from "./types";

export const mockCategories = [
  "Electronics",
  "Furniture",
  "Office Supplies",
  "Hardware",
  "Software",
  "Accessories",
];

export const mockProducts: Product[] = [
  // {
  //   id: 1,
  //   name: "Wireless Mouse",
  //   costPrice: 15.99,
  //   salesPrice: 29.99,
  //   stockMin: 10,
  //   stockMax: 100,
  //   currentStock: 45,
  //   productStatus: "ACTIVE",
  //   category: "Electronics",
  // },
  // {
  //   id: 2,
  //   name: "Ergonomic Office Chair",
  //   costPrice: 120.0,
  //   salesPrice: 249.99,
  //   stockMin: 5,
  //   stockMax: 50,
  //   currentStock: 12,
  //   productStatus: "ACTIVE",
  //   category: "Furniture",
  // },
  // {
  //   id: 3,
  //   name: "USB-C Hub",
  //   costPrice: 25.5,
  //   salesPrice: 49.99,
  //   stockMin: 15,
  //   stockMax: 80,
  //   currentStock: 8,
  //   productStatus: "ACTIVE",
  //   category: "Electronics",
  // },
  // {
  //   id: 4,
  //   name: "Mechanical Keyboard",
  //   costPrice: 65.0,
  //   salesPrice: 129.99,
  //   stockMin: 8,
  //   stockMax: 60,
  //   currentStock: 23,
  //   productStatus: "ACTIVE",
  //   category: "Electronics",
  // },
  // {
  //   id: 5,
  //   name: "Standing Desk",
  //   costPrice: 280.0,
  //   salesPrice: 599.99,
  //   stockMin: 3,
  //   stockMax: 20,
  //   currentStock: 5,
  //   productStatus: "ACTIVE",
  //   category: "Furniture",
  // },
  // {
  //   id: 6,
  //   name: "Notebook Set",
  //   costPrice: 8.99,
  //   salesPrice: 19.99,
  //   stockMin: 20,
  //   stockMax: 200,
  //   currentStock: 150,
  //   productStatus: "ACTIVE",
  //   category: "Office Supplies",
  // },
  // {
  //   id: 7,
  //   name: "Monitor Arm",
  //   costPrice: 45.0,
  //   salesPrice: 89.99,
  //   stockMin: 10,
  //   stockMax: 40,
  //   currentStock: 2,
  //   productStatus: "INACTIVE",
  //   category: "Accessories",
  // },
  // {
  //   id: 8,
  //   name: "Desk Lamp",
  //   costPrice: 22.5,
  //   salesPrice: 44.99,
  //   stockMin: 12,
  //   stockMax: 70,
  //   currentStock: 34,
  //   productStatus: "ACTIVE",
  //   category: "Accessories",
  // },
];
